### ISSUE TITLE
[1.12.2] Adding all genes via commands causes this weird stutter for mobs. You also cannot break blocks, etc.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#109]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.17
jei_1.12.2-4.15.0.291

-----

Hope the gif is viewable. 
https://i.imgur.com/CAZi0lG.mp4

I am near some Sheep as well as some Zombie Pigmen that I spawned in... everything is working normally.... until I give myself all genes via commands. Now upon doing this... mobs will twitch, stutter about, as if you were lagging.

What's not shown in the gif is me breaking blocks. Basically... when you break a block... it instant respawns. You also cannot use /kill as it will say that it killed you... but nothing happens.

Perhaps there might be a gene that causes this weird thing to happen? I'll have to do some grinding to test out each individual gene, however.

**Comment by clubpetey** [comment]
The twitching and the block-reappearing are signs of the server not able to catchup.  There is too much processing in the ticks.  Here's a couple of things to check:

1. Do you have "grant genes to mobs" on in the config?  Unless you are using that, turn it off.
2. Remove the Bio-luminescence gene only, this particular gene is CPU intensive as it is effectively a moving light source.  This one gene may be the cause of the slow-down. There are other ways to implement it, but they it doesn't work with certain light source-dependent things.

In GENERAL with the list of genes now twice the size of a few months ago. I don't think it is expected that you would have every gene on one player.  Having said that, I will be profiling and optimizing the genes in the next release to better deal with this type of issue.

**Comment by SonicX8000** [comment]
1
Would it be this?
`B:"Allow giving other entities genes"=false`

2
What is the exact name for the Bio-luminescence Gene? In the config I set that to false and did a give all genes and it still did what was shown in the gif. I drew my blood while lagging and managed to view the NBT and it showed that 'Bioluminescence' was in there.

A closer look... apparently the viruses are in there as well. Isn't there a virus that instantly kills?

***EDIT***
After looking into the code... 'DEAD_ALL' which is the Black Death Virus is the cause of the bug. I added only that gene and got what's shown in the gif to occur. My guess is that it kills me but I'm not exactly dead.

I've also added 'BIOLUMIN' which is the Bioluminescence gene and everything appears as normal... only I'm not giving off any light. Another one I tried was 'LEVITATION' which is the Levitation Virus and that did nothing for me, unless it doesn't affect players or something.

**Comment by clubpetey** [comment]
1. Yes
2. Thanks for the extra details. Turning off the gene in the config will not remove the gene from your body, it will just make the effect not work.  So that is expected.

In your video, The DEAD_ALL virus is fighting with the SLIME and the REGENERATION genes.  But the big issue is the negative genes probably shouldn't be added with the "all" command, so I will make that change.  I'll see look into why you are not dead with the gene by ltself, I just tested it and it killed me quick... It could be a conflict with another mod...

Also, BIOLUMIN isn't really obvious unless you are in the dark.  You can increase the bio-lumin light level in the config.  The default is 12, but setting it to 15 might make it more obvious.  The light is actually at head-level, so it's usually off the ground a bit.

(be sure to turn BIOLUMIN back on in the config)

**Comment by TheUnderTaker11** [comment]
Aw, man, I had those EXACT symptoms for something in Demonic Intervention, but I can't for the life of me remember the cause of it. All I remember is it was something I wouldn't expect to cause it, cause it's not server lag causing that, the TPS was perfect, but something else.

EDIT: Oh didn't realize the cause was already found, I just read these in my email.

**Comment by SonicX8000** [comment]
I tried DEAD_ALL with only Genetics Reborn & JEI added. Still got the 'dead but not exactly dead' effect. This was in a new world.

As for the BIOLUMIN... a derp on my part as I had that gene set to false in the config. It works after putting it back to true.

**Comment by clubpetey** [comment]
Ok, I'm investigating DEAD_ALL right now.
