### ISSUE TITLE
Organic Matter and DNA Helixes Do Not Stack in Machines or Inventory

### ISSUE THREAD

**Issue by BigWill079** [TheUnderTaker11/GeneticsReborn#112]

**Comment by clubpetey** [comment]
Organic matter from the diamond scraper will not stack due to the NBT tags.  other matter, cells, and helixes will stack as much as possible start with v1.15  For example all regular blaze cells will stack, but blaze cells with the BIOLUMIN focus will not stack with regular blaze cells.  The tooltips were updated to help explain what the differences are in stacks.
