### ISSUE TITLE
Step Assist not working.

### ISSUE THREAD

**Issue by Eldresh** [TheUnderTaker11/GeneticsReborn#126]
Multiplayer, Minecraft version 1.12.2, GeneticsReborn version 1.12(1.20)

Tried using syringe with only Step Assist in it and also tried giving Step Assist via command, neither worked. It seemed to inject just fine, but the actual step assist just... doesn't do anything. I do have autojump turned off, and it doesn't seem to work for anyone else in the game with me who has it either.

Another mod I had installed that gives it via an item worked just fine, so its got to be something going on with this mod.

**Comment by clubpetey** [comment]
What is the other mod that gave you step assist?  It could be fighting with the gene and overriding it.

**Comment by Eldresh** [comment]
The other mod is ProjectE, and it doesn't give you step assist so much as one of its items has a step assist toggle on it. Even with nobody wearing it step assist from GeneticsReborn didn't work.

**Comment by TheUnderTaker11** [comment]
Hm I do doubt a big mod like projectE would make a rookie mistake like
that, but you seem to misunderstand the question.

Any mod that could at any point in any way give you step assist could be
the culprit, as they might ONLY be checking if their item/whatever is
giving it, and canceling out Genetics Reborn's step assist since their
specific thing isn't giving it.

Happens a lot with flight added by inexperienced modders.

If you have Botania or Cyberware or Draconic evolution or any other step
assist, try ProjectE's along with another of any of those step assist, and
if they work then it is probably Genetics mod at fault, and if only 1 but
not any more of the others works, its at fault of the mod that step assist
works with.

**Comment by TheUnderTaker11** [comment]
And to be clear, try them 1 at a time, not all at once.

**Comment by Eldresh** [comment]
Yeah, ProjectE is the only other source of step assist in our mods. We're not using Botania, Cyberware, Draconic Evolution, or anything else other than ProjectE than grants it. 

It'll be a day or two before I can go through and test it. I'll do once with just Genetics Reborn, once with just ProjectE, and then with just Genetics Reborn and ProjectE, but once I am able to I'll make sure to update here with what I manage to figure out.

**Comment by TheUnderTaker11** [comment]
When you do, go ahead and give us your whole mod list as well just in case.

**Comment by clubpetey** [comment]
I looked at the ProjectE source.  It is interfering with the stepAssist gene. There is a routine in projectE that checks if it thinks there should be step assist based on its items only, and if not, send a packet to the client re-settting the stepHeight.  This disables our gene's function.  The check in ProjectE runs every tick, so even if I attempted to detect the change, and undo it.  The two mods would just fight back and forth, setting and unsetting the value.  ProjectE doesn't keep track if it was the one to set the stepHeight or not, so it will roll over other mods as well.

Looking at the code there is no way to turn off their check either.  So even disabling the item in ProjectE, won't stop the per-tick check.  It also looks like ProjectE may interfere with the Flight gene, as this same process is used there too.

I'll open a ticket in ProjectE, maybe they can re-write some of this to support other mods adjusting stepHeight.
