### ISSUE TITLE
Quick Question/Clarification.

### ISSUE THREAD

**Issue by Keetarin** [TheUnderTaker11/GeneticsReborn#127]
How do I add mutations to modded mobs without making them default genes?
Do I need to do anything special? or do I just add it to its entry in the Mob Additions file and the mod will take it from there?
It would be helpful if the wiki contained information on how to set up modded mobs with genes and mutations.

**Comment by clubpetey** [comment]
You can add the mutations to mob like any other gene, but in order to use the mutation you must also have the pre-req gene.  The only mutations that do not have pre-reqs are Fly, Luck, and Invisibility.  So you can give a mob the THORNS gene, but your player still must have photosynthesis to use thorns.

**Comment by Keetarin** [comment]
Thanks, that was helpful information.
