### ISSUE TITLE
Mob Sight gene not working as intended 

### ISSUE THREAD

**Issue by xReckless** [TheUnderTaker11/GeneticsReborn#138]
Wiki page for mob sight says it makes mobs glow to the player, when the gene is obtained it makes the player themselves glow rather than mobs.
Latest forge + Genetics Reborn 
SS: https://gyazo.com/3f37463bb0777a6cb8b5f2f82350cc42

**Comment by DartisXUI** [comment]
i can confirm this happens to me - i also have the glowing effect for some reason...

https://www.dropbox.com/s/lscxp3kw8wdetlf/2020-02-20_18.47.36.png?dl=0

The next pic was taken in the hunting dimension to compare seeing mobs

https://www.dropbox.com/s/c1v6yauvvenpo92/2020-02-20_18.52.52.png?dl=0

**Comment by DartisXUI** [comment]
ok so i added a few extra genes from ender dragon (health and fire - testing health but breathe doesnt seem to work with the designated keyboard short cut - and when i added two more - infinity and resistance - i now have invisibility for some reason...
well...
i sort of have invisibility - check pic for further info
https://www.dropbox.com/s/1xqv3u2j20i42wv/Almost%20Invisibile.png?dl=0
and as an after thought - heres my gene list
https://www.dropbox.com/s/vyb4puabibu03xp/Almost%20Invisible%20Gene%20List.png?dl=0

EDIT:
to reiterate, as invisibility is an mutation only, i do not know how i have this gene - except via a conflict between this non working gene (registering as the "Glowing" status with me outlined instead of the mobs), and the Resistance gene - invisibility didnt "show up" until after that was added...

the other thing that has been interesting, since giving myself resistance (after the more hearts gene from an enderman (1 extra set of hearts for 20 hearts total), i have received not only 1 additional extra set, but 2 additional extra sets of hearts (BLUE hearts = 40, i think)
im not sure, but i think these extra sets are coming from - or being absorbed from - my regenerations mod. the mod grants you a temporary set of 10 hearts to absorb damage after a regeneration occurs
more specifically, i can confirm these hearts are turning up after you accidentally or deliberately hit the Y key. this forces a regeneration to happen. currently i have blue hearts and testing this my hearts are trying to increase to light purple/pink in color. currently they reach abour 3 hearts filled then my regeration process hurts me and i 'reset' to blue - happened that way twice now

as this is getting sidetracked, do ytou want me to post this resistance/regeneration interaction on a separate issue?

**Comment by clubpetey** [comment]
Mob sight was functioning backwards, making the player glow, and not the mobs.  This has been corrected.
