### ISSUE TITLE
Shift click pulling items destroys leggings

### ISSUE THREAD

**Issue by Drase333** [TheUnderTaker11/GeneticsReborn#15]
When shift clicking to pull items from one of the genetics reborn machines (tested mostly on blood purifier), it caused the leggins I was wearing to disappear. Originally found the issue while playing in a modpack, but was able to isolate it down to Genetics reborn, as I tested it in vanilla with only genetics reborn v0.15 installed, as well as two separate mods to power it, on separate worlds, to make sure they weren't the cause (mekanism and ender io)

Edit: To clarify as well, I was using minecraft 1.10.2 with forge 2185

**Comment by TheUnderTaker11** [comment]
Let me start off with a "whoops". Probably should of seen that problem, but it just slipped my view. Sorry about that. v 0.16 with a fix for that should be up within 2-3 hours at the most. I already knew about the problem before you made this post, but was still doing some finishing touches on that and a few other shift click related things.
Also there were other problems with shift clicking that will also be fixed in 0.16, if you had noticed them or not.

**Comment by TheUnderTaker11** [comment]
Went quicker than I thought since I guess I already had re-done my shift clicking, but haden't put an update out yet for it since I was in the middle of something else. Regardless new fixed version is up now, should not have any more shift clicking problems hopefully.
