### ISSUE TITLE
1.23 Syringe Automation issue

### ISSUE THREAD

**Issue by maduin81** [TheUnderTaker11/GeneticsReborn#160]
When piping a syringe from the bottom of the blood purifier to right side of the plasmid injector and back through the bottom of the plasmid injector (loading multiple genes), the syringe will be inserted into the plasmid injector and immediately ejected before the new gene can be inserted.

It's possible I'm just doing this wrong, but I've tried multiple configurations with no change.

**Comment by TheUnderTaker11** [comment]
While this is a good suggestion to ease automation, this isn't a bug per-say, just a feature you assumed existed but doesn't. Since the machine works by having the syringe always be in the output slot, nothing is stopping it from being pulled out before any actual work is done.

But having it so automation only pulls out dirty syringes isn't a bad idea.

**Comment by maduin81** [comment]
Thank you for the response.  If changes are made to support this, I've not tested if it falls into that same category and it may already do this, but could the plasmid infuser also be made to only spit out completed plasmids?

**Comment by TheUnderTaker11** [comment]
I'll close this and make a more straightforward issue for ClubPetey to see.
