### ISSUE TITLE
Limit output slot of Plasmid Infuser and Injector

### ISSUE THREAD

**Issue by TheUnderTaker11** [TheUnderTaker11/GeneticsReborn#161]
Plasmid Infuser - Only allow completed plasmas to be pulled out with item pipes/hoppers.

Plasmid Injector - Only allow dirty syringes to be pulled out with item pipes/hoppers.

In reference to #160

**Comment by DartisXUI** [comment]
even if the input and output had separate configs for each machine

1 - you dump your organic matter into a chest piping into the first machine
2 - any encrypted helixes imputed into second
3 - any decrypted helixes can be stored into holding chest/storage
4 - either via filter on piping mod or by gen re's own design, any compatible genes auto extracted from chest, then imputed into next machine
5 - completed plasmids extracted ... etc

this is what i would ideally want to have set up
this is also what i tried to do using ender io "item conduits" and "item filters" but the conduits extract both the output and input items froim each machine last i tried - pre-mutations update

**Comment by 7eggert** [comment]
In (some) other mods, the IO is automatically limited to the apropriate slot: Input from any side to the input slot, pull out using the same enderio pipe when done. OTOH it's your mod, your rules.

@DartisXUI, you'll also want to mutate genes. Don't invest too much into your first setup.

**Comment by DartisXUI** [comment]
last time i tried to automate gen re (a few servers ago - 1.15), it didnt work as i mentioned above.

in my current server ive almost finished my mutations (ive been using the broken 1.23 update (for instant low temp incubator processing) and have come across the strength from polar bears bug that makes it resistance instead - fixed in 1.24). i wont update until ive gone through everything i want to and can do...

myself, i have started on viral agents, but the first one i tried didnt work (Cure - the emerald heart helixes wont process), so will be going through them all to make sure if there are others before reporting (also double checking what i might have done wrong)

**Comment by clubpetey** [comment]
All the machines follow the same inventory access pattern, down & right is output, all other sides are input.  The incubator is an execption, it has specifically configured sides due to all its different inputs.

Pipe systems like EnderIO and Xnet typically do not respect facings though, they want to access all inventories from all sides, so you don't need to connect to multiple sides of the same block.  Machines in mods like Mekanism or Themal Expansion use side-configurations to force certain inventories access from certain sides.  

It's unlikely I'll implement roll-your-own-side-configuration any time soon, so the best solution would be to use filter on your pipes to only get/put what you want out of each machine.  All major item transfer systems have a filter or blacklist option.  

I do like the idea of an auto-eject though.  This saves people from using hoppers and that means less tile entities and less lag.  So I will create a new ticket to add an auto-eject option to the machines down-facing.
