### ISSUE TITLE
[1.12.2] EFFICIENCY gene doesn't seem to boost break speed.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#175]
This was posted in the discord but I figure I put it in as an issue.

> It seems the EFFICIENCY gene isn't boosting break speed, kinda? Some tests done by using a Diamond Pickaxe on a Stone Block & A Diamond Shovel on a Grass Block. Using The One Probe to view the Progress towards breaking a block.
> 
> Diamond Pickaxe VS Stone Block
> "No  gene": 17%, 35%, 53%, 71%, 88%, BREAK
> "EFFICIENCY": 17%, 35%, 53%, 71%, 88%, BREAK
> "EFFICIENCY_4": 17%, 35%, 53%, 71%, 88%, BREAK
> 
> Diamond Shovel VS Grass Block
> "No  gene": 44%, 88%, BREAK
> "EFFICIENCY": 44%, 88%, BREAK
> "EFFICIENCY_4": 44%, BREAK to BREAK
> 
> Something seems off... although EFFICIENCY_4 shows a hint of instant breaking Grass Blocks with a Diamond Shovel but there's no sign of any boost when mining Stone Blocks with a Diamond Pickaxe.
> 
> For HASTE there's a boost being applied although that grants the Haste Potion Effect.
> 
> Diamond Pickaxe VS Stone Block
> HASTE: 21%, 42%, 64%, 85%, BREAK
> HASTE_2: 24%, 49%, 74%, 99%, BREAK
> 
> Diamond Shovel VS Grass Block
> "HASTE": 53%, BREAK
> "HASTE_2": 62%, BREAK

=====

I tested this again and it still occurs in "geneticsreborn-1.12-1.26".

**Comment by clubpetey** [comment]
Fixed in 1.27, Efficiency was being calculated on the server correctly, but the client does not know about the efficiency boost, and since the client sends then block-break message to the sever, the efficiency wasn't being factored in correctly.  

After fix, Testing with diamond pickaxe on obsidian, w/o gene it takes 10 seconds to break a block, with the standard EFFICIENCY gene it takes 5 seconds.  with EFFICIENCY_4 mutation it takes 2 seconds.

**Comment by clubpetey** [comment]
Haste applied via potion is intended, and does work correctly.
