### ISSUE TITLE
Suggestion - Redstone signal output from Advanced Incubators

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#178]
when the advanced incubators finish processing on low temp mode, could they emit a redstone signal so we can add a redstone activated lamp or note block (modded or vanilla), so the lamp will light up/sound off?

**Comment by DartisXUI** [comment]
or maybe just add a sound to the completion of the processing of the advanced incubators - like the sound the brewing stand makes maybe?

**Comment by DartisXUI** [comment]
or change the color of the front panel symbol to green
its red atm, so red when processing, green when not

i dont know - whatevers easier to implement, but some sort of notification system would be great imo

**Comment by clubpetey** [comment]
Good idea, and after a crash-course in redstone and blocks, the Incubator will now push out a redstone signal to all sides except the bottom when brewing is done. after the last potion is removed from the output, the redstone will drop to 0.

The bottom is not triggered so that hoppers can still be used with the incubator to extract the output.  However, if you want to use hoppers you must be sure that the blocks around the hopper do not have redstone on them, as the redstone on the block will be picked up by the hopper, and deactivate it.
