### ISSUE TITLE
1.26 - Lost potions in processing while harvesting advanced incubators

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#179]
i noticed only one of my adv incubators with correct shift click potions into separate slots  into it - and its chorus fruit slot was empty, so i decided to harvest all 4 adv incubators to see if they stack and whether replacing them would fix the others...

not only did the test fail in all aspects - still only one adv incubator has th4e shift click working and chorus fruit slot free, but i also lost all potions being processed at the time...

side points:
a - is it worth making new machines? will they all work like the one does (this worked for another mod that got an update)
b - also, should i loose all progress if i harvest the adv incubators?

**Comment by clubpetey** [comment]
There were general problems with the shift-click routines, so they have been re-written in 1.27.  Example: shift-clicking a stack of water potions will now spread out the potions correctly across the input slots.  However the chorus fruit is tricky, because it can be an ingredient or fuel, so it will fill the ingredient slot first, then the fuel slot.  So be sure to add your ingredients first. 

If you are using pipes, this isn't a problem, as the front/back is fuel and the sides are input (bottles), ingredient in the top, outputs out the bottom.

1.27 also fixes the drops when the incubator was broken.  I just flat out never wrote that code :/
Breaking the Incubator will not drop your ingredients, inputs, and fuel.  To answer your questions:

a. You should not need to make new machines.  the code change should apply automatically
b. You should not lose the items in the incubator, but you will lose any "processing" progress when you break it, so it will not pickup where it left off.  The incubuator also does not retain energy stored in it.  None of the machines in this mode do that.
