### ISSUE TITLE
Crafting Clash

### ISSUE THREAD

**Issue by maxgestic** [TheUnderTaker11/GeneticsReborn#189]
The recipe of the cell analyzer clashes with TV in Clayfish furniture pack

**Comment by clubpetey** [comment]
It's easy enough to change the recipe, but they've been the way they are for a long time.  My default answer would be "Installed CraftTweaker and change the recipe" as avoiding all mods and their recipes would be endless.

We could also take the route of many machine mods and create a generic "machine block" that is used only to craft our recipes, this fixes conflicts, but I never liked the unnecessary crafting step.

@TheUnderTaker11 what's your opinion on change recipes due to mod conflicts?

**Comment by DartisXUI** [comment]
We use cells in the other machine recipes, maybe make the first machine craft with 1 x organic matter

**Comment by clubpetey** [comment]
Changed to use a glass syringe in 1.29.
