### ISSUE TITLE
Server crashed again

### ISSUE THREAD

**Issue by RickardETW** [TheUnderTaker11/GeneticsReborn#19]
I used geneticsreborn-mc1.10.2-v0.18.1 but it still crashes the server
New Crash Log: https://justpaste.it/12lb1

**Comment by TheUnderTaker11** [comment]
Damn, alright I'll have more time to test within like 30 min so I'll actually get the the problem. I had tried what I hoped would work and went on faith that it would, ill placed faith it seems. I'll take down that version and make sure this next version ACTUALLY works...
It takes a lot of time since I don't have a server I can use in my dev environment.

**Comment by TheUnderTaker11** [comment]
Okay it took some effort but I got a test server and client set up and was able to start and join the server with my fix (Which was a one line fix btw). But now any other server related problems I should be able to test a lot quicker! Going to release a new file soon, and I'll close this issue when I do

**Comment by TheUnderTaker11** [comment]
Just uploaded file, and like I said, actually had time to test it and everything this time, so your server should not crash and should be join-able.
If you get any other bugs don't hesitate to report them!
