### ISSUE TITLE
[Suggestion] hotkey to toggle flight

### ISSUE THREAD

**Issue by pp-pp-pp-pp** [TheUnderTaker11/GeneticsReborn#20]
I usually just like to use my elytra, but creative flight is very useful for building, so I am requesting a hotkey to toggle flight, (default would be on)

**Comment by TheUnderTaker11** [comment]
I would like to keep the keybinding down to a bare minimum. However I will add the option to right click the Anti Field Orb and have it also disable flight since you requested it. I'll also see if I can make it be a Bauble so it won't always have to take up an inventory spot.
I wasn't aware the elytra didn't work while flight was enabled.

**Comment by TheUnderTaker11** [comment]
Finished adding it to the orb. Just right click and it will glow enchanted-like, which means it is also disabling flight. Will be in as soon as next version is released.
