### ISSUE TITLE
Cannot inject a metal syringe containing the gene.

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [TheUnderTaker11/GeneticsReborn#237]
I tried to inject the Wooly gene into the sheep after drawing blood from the sheep with a metal syringe, purifying it, and then injecting the Wooly gene into that syringe, but it would not click and inject.

I think this is a bug, because I couldn't find any configuration item from Config, except to set the metal syringe setting to true

version: geneticsreborn-1.12-1.32

**Comment by CocoPouleto** [comment]
shift+click to inject

**Comment by DartisXUI** [comment]
Not sure if you figured this issues out yet.

1. Giving genes to mobs is default to false due to high lag iirc, so doing this wouldn't work unless you have changed that.

2. After injecting a gene into a Syringe  you have to purify it Again. If your Syringe says contaminated you must purify it.

3. And as stated above, RClick draws blood. Shift RClick injects it.
