### ISSUE TITLE
My Gene machines is not accepting rf

### ISSUE THREAD

**Issue by ghost** [TheUnderTaker11/GeneticsReborn#44]
Playing a space astronomy 2 with some freinds and im using a solar panel from mekanism to get power to my machins, and i use galaticraft aluminium wires. The geneti machines is not getting power from any of them.

**Comment by TheUnderTaker11** [comment]
This is an ongoing problem for the 1.11.2 version that I have yet to get time to fix. For now you can just set the machines to not use power if there is no other option. (Latest version adds a config option for this)

**Comment by ghost** [comment]
I found that using mekanims cables makes them work, if thats something

**Comment by TheUnderTaker11** [comment]
It's because my mod right now uses CoFH power, which a lot of mods moved away from for forge energy for obvious reasons. I wasn't able to get forge energy to work in early stages so I scrapped it an now am feeling the consequences of that. Would be open to someone making a pull request to my just updated 1.11.2 branch with a fix for that.

**Comment by alothmanmoe** [comment]
Fixed in the 1.12 version, anything below 1.12 will no longer be updated
