### ISSUE TITLE
so the first bug 

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#5]
it crashed when i right clicked on a villager with the diamond scraper 
[crash-2017-01-11_22.07.41-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/700058/crash-2017-01-11_22.07.41-server.txt)

**Comment by mcpecommander** [comment]
i think the issue is not with the villager himself as it only crashed when the cell dropped on the ground 
[crash-2017-01-11_22.22.33-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/700075/crash-2017-01-11_22.22.33-server.txt)
[crash-2017-01-11_22.19.34-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/700074/crash-2017-01-11_22.19.34-server.txt)

and here is the other two crashes from the same bug

**Comment by TheUnderTaker11** [comment]
Alright, sounds like maybe villages have more info on them than I accounted for, give me about 30 min and I'll be able to test this myself.

**Comment by TheUnderTaker11** [comment]
Bug fixed, some leftover code from some kind of test was causing the crash. Will release new fixed version after you respond to the texture thing.
Hopefully since that is only for cloning, which I haven't implemented yet, no one actually trying to play this mod will have run into the problem. Thank you so much for the report!
