### ISSUE TITLE
[suggestions]

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#6]
I will start adding some ideas to help some small details here 
the first is to make textures for the "machines" 
the second is to add a way to generate RF even if in creative only so that when I test it out , I do not have to download another mod to get RF

**Comment by TheUnderTaker11** [comment]
Not sure what you mean by make textures for the machines? They have textures. Is it showing purple and black for you or what, because I know it's not just me seeing the textures(What they should look like can be found on the wiki page). Another note is the front face texture will face towards you, even if you are above or below where you placed it. For example, if you jump stack a Cell Analyser, the magnifying glass on it will be facing up

On the second part, yes I know, and its on my to-do list, but I just wanted to get a beta out that people could play as quickly as possible, as to catch bugs earlier and get it's name out there. I plan to just make a simple coal generator so if needed you can run the stuff without other mods.

**Comment by mcpecommander** [comment]
Oh I am sorry that I took a bit more time to answer but I live in another time zone from America (supposedly you live there. If not I am sorry I assumed that) 
I was going to sleep and answer tomorrow but you replied too quickly and so I was talking that these textures are really plain and you should improve them later on but I am sorry if I wrote something that led you to assume that. However thanks for the fast reply and I will definitely continue testing the mod tomorrow

**Comment by TheUnderTaker11** [comment]
Yes I am from the US, so you were right in assuming. I would make the textures better if I could, but I honestly don't know how. I am a coder at heart, and all these textures you see were made by me, but I am by no means an artist. If anyone ever wants to do textures for me than I am 100% open to that, as long as all the block textures keep a common theme.
To sum it up, my problem is I have little to no artistic talent, so what you see is about the best I can do for now.
