### ISSUE TITLE
[Suggestion] New genes

### ISSUE THREAD

**Issue by NatsuDess** [TheUnderTaker11/GeneticsReborn#60]
Hi there,

I have a new gene to propose.

Skeletton can give a Infinity gene same on advanced genetic mod if is possible

And a modification for the teleportation of gene of Endermen, I think the distance is so short, maybe make same when we use a ender pearl?

I hope this is possible :)

**Comment by TheUnderTaker11** [comment]
I will not be increasing the teleport range since it is already very powerful in it's current state. You can use it to get in and out of virtually anything already, and keeping the distance short also maximizes its practical use when moving around a base. 

Infinity is something I really should have added but never did.

**Comment by NatsuDess** [comment]
Thx for answare

I undrstand for Enderman teleport, no problem, i can think is so OP for most situation as well

For infinity, I hope u can give that in next feature

Good mod anything and i love ur mod actually and I use it again.
