### ISSUE TITLE
Shift-clicking an helix into the Plasmic Infuser dupes it.

### ISSUE THREAD

**Issue by soronthar** [TheUnderTaker11/GeneticsReborn#67]
Ver 1.12-1.09

When  Shift-clicking an helix into the Plasmic Infuser a new helix appears inside and its consumed and added to the plasmid, but the original helix remains in the player inventory, effectively dupping it.

**Comment by Anarchy079** [comment]
actually that goes for anything you throw into the machines

**Comment by GamertechAU** [comment]
Got this too. Shift-clicking 1 item adds an entire stack to the machine plus another stack in your bag, and usually deletes a random item from your inventory at the same time.
Fairly gamebreaking atm.

**Comment by GamertechAU** [comment]
Any chance of getting a release with this specific PR in it? I'm planning to release a pack with this mod in it soon, and this dupe/delete issue is the only major bug remaining. I don't want to make it too easy for players :P

**Comment by TheUnderTaker11** [comment]
@Gamertech A release with dupe fixes is now up. I honestly hadn't realized that Abused never uploaded a file with this fix or I would absolutely have done it myself. Sorry that you had to wait until someone else came along as started coding for it as well, I just never knew of this PR's existence since I don't check it often and only know about the stuff I read the email updates of.

**Comment by GamertechAU** [comment]
Oh wow. Thought this was long since done for. Tested the fix and it's no longer duping items.

Thanks for the upload!
