### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by Rightfuldeathray** [TheUnderTaker11/GeneticsReborn#70]
genetics reborn minecraft version 1.12
there seem to be a variety of problems with this mod 1 is #67 the fact that shift clicking a valid input into any machine always results in duplication and sometimes duplication occurs anyways, and the other which is a bigger problem is #69 if something is shift clicked and duplicated there is a chance that an item on the player's hot bar is destroyed, this can be pretty annoying if you carry around a backpack like me and keep tons of valuables inside. I already lost this bag do to a series of odd events and a small amount of mod incompatibility, but to restore the bag and start remaking a genetically modified pet that I stored as an item in said bag, only to have it deleted and start all over again... 
anyways a disclaimer of these glitches would be nice until they can be resolved that way people at least have a heads up

**Comment by Darkmega18** [comment]
Yeah, this stuff. it's still happening at this point in time.

I shiftclick genetic material into machines and it dupes straight up to a stack of 64 of the one piece and sometimes annihilates other things in my inventory due to it's glitching and spawning of said bonus items.

When is the apparent stable 1.12.2 that the recent method was merged into to be released? I'd like to tinker with this in my modpack and make quests related to it etc, but I don't want to start highlighting it until it stops bugging and making issues like it is. :V

**Comment by Cosmicfox** [comment]
1.12.1 is the one I am experiencing issues with like that and 2 machines exactly the same.. sad that it is broken.. >:^(

**Comment by clubpetey** [comment]
Fixed both sub issues.
