### ISSUE TITLE
[1.12.2] Dragon Health Crystal doesn't account for vanilla damage reductions, like Armor, Resist, Protection, etc.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#89]
Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 3
extrautils2-1.12-1.9.9
geneticsreborn-1.12-1.12
jei_1.12.2-4.15.0.279

-----

The 'Ender Dragon's Health' allows you to use the Dragon Health Crystal to absorb the damage taken at the cost of it's durability... however I've noticed that vanilla damage reductions won't apply when the crystal absorbs the damage. These reductions are...

Any Armor.
Any Protection Enchantments.
Any Resist Potion effects.

I used Extra Utilities' Mechanical User which was equipped with a Sharpness V Diamond Axe so it buffs it's damage to 12.0. I used that Cheat Tool to enable all the genes besides the Resist Gene as that was disabled in the config while doing some testing.

***Tests***
Nothing worn: 0 Armor, 0 Toughness
12 Damage Taken, if using the Crystal... shows 988/1000 Durability.

Diamond Chestplate '+8 Armor, +2 Toughess':
10 Damage Taken, if using the Crystal... shows 988/1000 Durability.

Protection IV Diamond Chestplate '+8 Armor, +2 Toughess':
8 Damage Taken, if using the Crystal... shows 988/1000 Durability.

Resistance IV effect, nothing worn:
2 Damage Taken, if using the Crystal... shows 988/1000 Durability.

-----

Modded Damage Reductions do appear to work correctly as their damage reductions apply on the Crystal. To name a few mods...

***Tests***
RPG Inventory's Buff'd Gloves, +20% Damage Reduction.
10 Damage Taken, if using the Crystal... shows 990/1000 Durability.

Angel of Vengeance's Shield of Faith spell, +50% Damage Reduction.
6 Damage Taken, if using the Crystal... shows 994/1000 Durability.

**Comment by TheUnderTaker11** [comment]
I appreciate the work you put into testing various methods. The only thing that logically MIGHT reduce it from the vanilla stuff is potion effects. Armor intentially does not affect the amount of damage taken by the crystal. The modded things only work because they reduced the base damage you take by some percent.

@clubpetey It's up to you if you want to make the damage to the crystal happen after potion effects. If there is no event after potions but before armor calculations for damage taken (don't think there is), it wouldn't be that hard to make a special case for resistance, since it just makes you take 20% less damage per level of resistance.

**Comment by SonicX8000** [comment]
Ah, it's intended? Thought it was bugged due to what the description says on the wiki about the Ender Dragon's Health.

**Comment by clubpetey** [comment]
Z-Tunic, thanks again for your analysis, since the Dragon Crystal is taking the full damage, I would expect that the armor is not damaged when being hit.  If the armor is taking damage AND the Crystal is taking full damage, I would see this as a bug.  Did you happen to notice if the armor took damage?

**Comment by SonicX8000** [comment]
Armor doesn't appear to take any damage, although I'm unsure if energy-like durability will still take damage, however.

I'll take a look at that after I get back from the store.

*EDIT*
That took awhile... but energy-like durability doesn't take damage if absorbed by the Crystal either.

**Comment by clubpetey** [comment]
Thanks for the response, Since the crystal blocks the armor from taking damage, it makes sense that it receives the full damage.  I believe this is working as intended.
